"use strict";

//redis连接信息
var REDIS_SERVER_IP = '192.168.1.245';
var REDIS_SERVER_PORT = '6379';
var REDIS_SERVER_PASSWORD = '335577';
var REDIS_SERVER_CONNECTION_COMMON_COUNT = 3;
var REDIS_SERVER_CONNECTION_PUBLISHSER_COUNT = 2;
//mongodb连接信息
var MONGODB_SERVER_IP = '192.168.1.245';
var MONGODB_SREVER_PORT = '27017';
var MONGODB_SERVER_DATABASE = 'JoJoClouds';
var MONGODB_SERVER_USER = 'test';
var MONGODB_SERVER_PASSWORD = 'test';
var MONGODB_SERVER_CONNECTION_COMMON_COUNT = 2;
//lunchserver配置信息
var LUNCH_SERVER_LISTEN_PORT = 3001;
var LUNCH_SERVER_DATA_EXPIRE_TIME = 6 * 3600;
//日志记录方式
var LOG_MODE = 'console';

exports.REDIS_SERVER_IP = REDIS_SERVER_IP;
exports.REDIS_SERVER_PORT = REDIS_SERVER_PORT;
exports.REDIS_SERVER_PASSWORD = REDIS_SERVER_PASSWORD;
exports.REDIS_SERVER_CONNECTION_COMMON_COUNT = REDIS_SERVER_CONNECTION_COMMON_COUNT;
exports.REDIS_SERVER_CONNECTION_PUBLISHSER_COUNT = REDIS_SERVER_CONNECTION_PUBLISHSER_COUNT;
exports.MONGODB_SERVER_IP = MONGODB_SERVER_IP;
exports.MONGODB_SREVER_PORT = MONGODB_SREVER_PORT;
exports.MONGODB_SERVER_DATABASE = MONGODB_SERVER_DATABASE;
exports.MONGODB_SERVER_USER = MONGODB_SERVER_USER;
exports.MONGODB_SERVER_PASSWORD = MONGODB_SERVER_PASSWORD;
exports.MONGODB_SERVER_CONNECTION_COMMON_COUNT = MONGODB_SERVER_CONNECTION_COMMON_COUNT;
exports.LUNCH_SERVER_LISTEN_PORT = LUNCH_SERVER_LISTEN_PORT;
exports.LUNCH_SERVER_DATA_EXPIRE_TIME = LUNCH_SERVER_DATA_EXPIRE_TIME;
exports.LOG_MODE = LOG_MODE;
